### ISSUE TITLE
This isnt an Issue!!!

### ISSUE THREAD

**Issue by gibetnicht** [KinDR007/Victron-MPPT-ve.direct-to-MQTT#2]
but I do not know how to communicate with you!

I plan to use your code with an Victron Smart Shunt. It also have victron.direct. My question is, if this is possible with your code. I have seen, that the model does not exist in the code.

It would be fine to hear from you. My mailadress is gibetnicht@gmail.com.

Thanks and stay healthy.

**Comment by KinDR007** [comment]
hi for smart shunt i have a version for esphome by slightly modifying the gains mqtt if needed [https://github.com/KinDR007/VictronSmartShunt-ESPHOME](url)

**Comment by KinDR007** [comment]
![E511B4E4-D6B5-4F52-8FF7-B216A4BB56AC](https://user-images.githubusercontent.com/61905170/130349238-88f08b10-0ff7-4fec-9eb2-ca630cf23556.jpeg)
