### ISSUE TITLE
please add SmartShunt product :)

### ISSUE THREAD

**Issue by bodforss** [KinDR007/Victron-MPPT-ve.direct-to-MQTT#4]

**Comment by KinDR007** [comment]
Hi unfortunately i don't have this product so i have no way to tune it.  therefore, I do not plan to add it yet

**Comment by bodforss** [comment]
hi! i actually found the PID while tinkering with the raw output from the SmartShunt. added the following line, and.. SUCCESS! :)

        case 0xA389 : client.publish("Victron/PID", "SmartShunt");  break;

The SmartShunt now deliver Voltage, Current, Firmware and PID via MQTT over to my HA :)

best regards

**Comment by bodforss** [comment]
case closed, from my point of view. its up to you if you want to merge it. ;)

**Comment by KinDR007** [comment]
> hi! i actually found the PID while tinkering with the raw output from the SmartShunt. added the following line, and.. SUCCESS! :)
> 
> ```
>     case 0xA389 : client.publish("Victron/PID", "SmartShunt");  break;
> ```
> 
> The SmartShunt now deliver Voltage, Current, Firmware and PID via MQTT over to my HA :)
> 
> best regards

Nice work

**Comment by KinDR007** [comment]
> case closed, from my point of view. its up to you if you want to merge it. ;)

Done!

**Comment by KinDR007** [comment]
> hi! i actually found the PID while tinkering with the raw output from the SmartShunt. added the following line, and.. SUCCESS! :)
> 
> 
> 
>         case 0xA389 : client.publish("Victron/PID", "SmartShunt");  break;
> 
> 
> 
> The SmartShunt now deliver Voltage, Current, Firmware and PID via MQTT over to my HA :)
> 
> 
> 
> best regards

Hi,
I now testing SmartShunt (for esphome) ![image](https://user-images.githubusercontent.com/61905170/120535563-6dad5280-c3e3-11eb-9d9c-36ffee5c69b8.jpeg)
