### ISSUE TITLE
Minor bugs in the home assistant YAML & Extension to read out the load current

### ISSUE THREAD

**Issue by LuckyTriple7** [KinDR007/Victron-MPPT-ve.direct-to-MQTT#5]
Hello, great Job !
I found 2 little Bugs in the YAML for Homeassistant:

![image](https://user-images.githubusercontent.com/60685158/120059462-0ba2c500-c052-11eb-9424-4e0a97d994ba.png)

correct is:
icon: mdi:battery
icon: mdi:current-dc

It is not necessary to connect GND. Only RX and TX need to be connected

With this extension, the load current is transmitted:

`else if (label == "IL")
    { // In this case IL chose to read load current
      val.toCharArray(buf, sizeof(buf));
      float floatValue = atof(buf);
      floatValue = floatValue / 1000;
      dtostrf(floatValue, len, 2, char_current);
      client.publish("Victron/Load current, I", char_current);
    }`

My Homeassistant YAML Code:

sensor:
  - platform: mqtt
    name: "Victron - Battery voltage"
    state_topic: "Victron/Battery voltage, V"
    unit_of_measurement: "V"
    icon: mdi:battery
    unique_id: sensor.text.victron.battery.voltage   
  - platform: mqtt
    name: "Victron - Battery current"
    state_topic: "Victron/Battery current, I"
    unit_of_measurement: "A"
    icon: mdi:current-dc
    unique_id: sensor.text.victron.panel.current   
  - platform: mqtt
    name: "Victron - Load current"
    state_topic: "Victron/Load current, I"
    unit_of_measurement: "A"
    icon: mdi:current-dc
    unique_id: sensor.text.victron.load.current   
  - platform: mqtt
    name: "Victron PV power"
    state_topic: "Victron/Panel power, W"
    unit_of_measurement: "W"
    icon: mdi:gauge
    unique_id: sensor.text.victron.panel.power 
  - platform: mqtt
    name: "Victron Panel voltage"
    state_topic: "Victron/Panel voltage"
    unit_of_measurement: "V"  
    unique_id: sensor.text.victron.panel.voltage
  - platform: mqtt
    name: "Victron Tracker operation"
    state_topic: "Victron/Tracker operation"
    unique_id: sensor.text.victron.tracker.operation
    icon: mdi:solar-power
  - platform: mqtt
    name: "Victron Yield today"
    state_topic: "Victron/Yield today, kWh"
    unique_id: sensor.text.victron.yield.today
    icon: mdi:gauge  
    unit_of_measurement: "kWh" 
  - platform: mqtt
    name: "Victron Yield yesterday"
    state_topic: "Victron/Yield yesterday, kWh"
    unique_id: sensor.text.victron.yield.yesterday
    icon: mdi:gauge  
    unit_of_measurement: "kWh" 
  - platform: mqtt
    name: "Victron - Maximum power today"
    state_topic: "Victron/Maximum power today, W"
    unique_id: sensor.text.victron.maximum.power.today
    unit_of_measurement: "W"
    icon: mdi:gauge    
  - platform: mqtt
    name: "Victron - Maximum power yesterday"
    state_topic: "Victron/Maximum power yesterday, W"
    unique_id: sensor.text.victron.maximum.power.yesterday
    unit_of_measurement: "W"
    icon: mdi:gauge          
  - platform: mqtt
    name: "Victron/Yield total, kWh"
    state_topic: "Victron/Yield total, kWh"
    unique_id: sensor.text.victron.yield.total
    icon: mdi:gauge  
    unit_of_measurement: "kWh" 
  - platform: mqtt
    name: "Victron Charge state"
    state_topic: "Victron/Charge state"
    unique_id: sensor.text.victron.charge.state
    icon: mdi:solar-power
  - platform: mqtt
    name: "Victron Error state"
    state_topic: "Victron/Error code"
    unique_id: sensor.text.victron.error.state
    icon: mdi:alert-circle-outline
  - platform: mqtt
    name: "Victron Day sequence number"
    state_topic: "Victron/Day sequence number"
    unique_id: sensor.text.victron.daysequencenumber.state
    icon: mdi:calendar-today

**Comment by KinDR007** [comment]
Hi, copy paste error sorry
